gUnknown_80DD388:: @ 80DD388
	.string "You have chosen to say farewell\n"
	.string "to this Pokémon.#P"
	.string "The Pokémon will leave its Friend Area.\n"
	.string "It will no longer be available for\n"
	.asciz "adventures. Is that OK?"
	.align 2, 0

gUnknown_80DD420:: @ 80DD420
	.string "If you say farewell to this\n"
	.string "Pokémon~2c it will be gone forever.#P"
	.string "You will never be able to get another one\n"
	.string "like it to join your team.\n"
	.asciz "Will you release it anyway?"
	.align 2, 0

gUnknown_80DD4C4:: @ 80DD4C4
	.string "#+$m1 joined the\n"
	.asciz "#+rescue team for adventures!"
	.align 2, 0

gUnknown_80DD4F4:: @ 80DD4F4
	.string "#+$m1 left the team to remain\n"
	.asciz "#+on standby in the Friend Area."
	.align 2, 0

gUnknown_80DD534:: @ 80DD534
	.string "#+$m1 became the leader\n"
	.asciz "#+of the rescue team."
	.align 2, 0

gUnknown_80DD564:: @ 80DD564
	.string "#+$m1 left\n"
	.string "#+the Friend Area.\n"
	.asciz "#+Bye-bye~2c $m1!"
	.align 2,0

gUnknown_80DD594:: @ 80DD594
	.string "#+The #C4$i1#R was\n"
	.asciz "#+handed over. "
	.align 2, 0

gUnknown_80DD5B8:: @ 80DD5B8
	.string "#+The #C4$i1#R was\n"
	.string "#+handed over.#P"
	.string "#+The #C4$i0#R was\n"
	.asciz "#+returned to the Toolbox."
	.align 2, 0

gUnknown_80DD60C:: @ 80DD60C
	.string "#+The #C4$i0#R was\n"
	.asciz "#+returned to the Toolbox."
	.align 2, 0

gUnknown_80DD63C:: @ 80DD63C
	.string "#+The #C4$i0#R was\n"
	.asciz "#+sent to storage."
	.align 2, 0

gUnknown_80DD664:: @ 80DD664
	.asciz "Stand By"
	.align 2, 0

gUnknown_80DD670:: @ 80DD670
	.asciz "Make Leader"
	.align 2,0

gUnknown_80DD67C:: @ 80DD67C
	.asciz "Join Team"
	.align 2, 0

gUnknown_80DD688:: @ 80DD688
	.asciz "Give Gummi"
	.align 2, 0

gUnknown_80DD694:: @ 80DD694
	.asciz "Give"
	.align 2, 0

gUnknown_80DD69C:: @ 80DD69C
	.asciz "Take"
	.align 2, 0

gUnknown_80DD6A4:: @ 80DD6A4
	.asciz "Say Farewell"
	.align 2, 0

gUnknown_80DD6B4:: @ 80DD6B4
	.asciz "Summary"
	.align 2, 0

gUnknown_80DD6BC:: @ 80DD6BC
	.asciz "Moves"
	.align 2, 0

gUnknown_80DD6C4:: @ 80DD6C4
	.asciz "Check IQ"
	.align 2, 0

gUnknown_80DD6D0:: @ 80DD6D0
	.asciz "Item: #C4$i0#R "
	.align 2, 0

gUnknown_80DD6E0:: @ 80DD6E0
	.asciz "%s"
	.align 2, 0

	.asciz "pksdir0"
	.align 2, 0
