gUnknown_80DFE4C:: @ 80DFE4C
	.string "Are you sure you want to replace the\n"
	.asciz "old  #CGWonder Mail#R with the new one?"
	.align 2, 0

gUnknown_80DFE9C:: @ 80DFE9C
	.string "This #CGWonder Mail#R has already been\n"
	.asciz "received."
	.align 2, 0

gUnknown_80DFED0:: @ 80DFED0
	.string "This #CGWonder Mail#R has already been\n"
	.string "received.\n"
	.asciz "You may not receive the same one again."
	.align 2, 0

gUnknown_80DFF2C:: @ 80DFF2C
	.string "Only #CGone piece#R of #CGWonder Mail#R can be held.\n"
	.string "Please receive it after completing any\n"
	.asciz "rescue mission in progress."
	.align 2, 0

gUnknown_80DFFA4:: @ 80DFFA4
	.string "The rescue team has quicksaved in\n"
	.string "a dungeon with a mission in progress.\n"
	.asciz "Please complete the mission first."
	.align 2, 0

gUnknown_80E0010:: @ 80E0010
	.string "The rescue team has quicksaved in\n"
	.string "a dungeon with a mission in progress.\n"
	.asciz "Mail cannot be deleted now."
gUnknown_80E0074:: @ 80E0074
	.asciz "Received the #CGWonder Mail#R!"
	.align 2, 0

gUnknown_80E0094:: @ 80E0094
	.string "Only #CGone piece#R of #CGWonder Mail#R can be held.\n"
	.string "Is it OK to replace the old #CGWonder Mail#R\n"
	.asciz "with the new one?"
	.align 2, 0

gUnknown_80E0108:: @ 80E0108
	.string "Your #CGJob List#R is full.\n"
	.asciz "Please select and delete unwanted mail."
	.align 2, 0

gUnknown_80E014C:: @ 80E014C
	.asciz "New Mail"
	.align 2, 0

gUnknown_80E0158:: @ 80E0158
	.asciz "Old Mail"
	.align 2, 0

	.asciz "pksdir0"
	.align 2, 0
