gUnknown_80E0184:: @ 80E0184
	.asciz " Thank you for rescuing me!"
	.align 2, 0

gUnknown_80E01A0:: @ 80E01A0
	.string " Thank you for rescuing\n"
	.asciz "#C5$m1#R!"
	.align 2, 0

gUnknown_80E01C4:: @ 80E01C4
	.string " Thank you for escorting me\n"
	.asciz "to #C5$m1#R! "
	.align 2, 0

gUnknown_80E01F0:: @ 80E01F0
	.string " Thank you for delivering\n"
	.asciz "the #C4$i0#R!"
	.align 2, 0

gUnknown_80E0218:: @ 80E0218
	.string " Thank you for getting me\n"
	.asciz "the #C4$i0#R!"
	.align 2, 0

	.asciz "pksdir0"
	.align 2, 0
