gUnknown_80DDBA8:: @ 80DDBA8
	.string " What you need to do is\n"
	.string "tell your friend--the one you rescued--\n"
	.asciz "this here password."
	.align 2, 0

gUnknown_80DDBFC:: @ 80DDBFC
	.string " All righty!\n"
	.asciz "Here~27s your #CGA-OK Mail password#R."
	.align 2, 0

gUnknown_80DDC30:: @ 80DDC30
	.string " Okeydoke! That~27s all done.\n"
	.asciz "Come around whenever you need."
	.align 2, 0

gUnknown_80DDC70:: @ 80DDC70
	.string " Okeydoke! I sent off your\n"
	.string "#CGA-OK Mail#R.#P"
	.asciz " Let me save your adventure."
	.align 2, 0

gUnknown_80DDCBC:: @ 80DDCBC
	.string "#+Please choose the Pokémon you want to\n"
	.string "#+send as a helper to your friend.\n"
	.asciz "#+(Its hold item will not be sent.)"
	.align 2, 0

gUnknown_80DDD2C:: @ 80DDD2C
	.string " ...Uh~2c no?\n"
	.string "There appear to be no Pokémon in your\n"
	.asciz "Friend Areas. What do you want to do?"
	.align 2, 0

gUnknown_80DDD88:: @ 80DDD88
	.string " You~27re sure you want to\n"
	.string "send this here Pokémon?\0" @ must stay .string due to encoding issues
	.align 2, 0

gUnknown_80DDDBC:: @ 80DDDBC
	.asciz " You~27re sure about this?"
	.align 2, 0

gUnknown_80DDDD8:: @ 80DDDD8
	.string " All righty. I need you to\n"
	.asciz "pick the #CGA-OK Mail#R you want to send."
	.align 2, 0

gUnknown_80DDE20:: @ 80DDE20
	.string " ...Uh~2c no?\n"
	.asciz "I don~27t see any #CGA-OK Mail#R here."
	.align 2, 0

gUnknown_80DDE58:: @ 80DDE58
	.string " Did you know? If you use\n"
	.string "a #CGGame Link cable#R~2c you can send\n"
	.string "a #CGhelper Pokémon#R to your friend.\0"
	.align 2, 0

gUnknown_80DDEC0:: @ 80DDEC0
	.string " Don~27t you worry. Sending\n"
	.string "a Pokémon doesn~27t mean it will go away.\n"
	.asciz "So! Want to send one to your friend?"
	.align 2, 0

gUnknown_80DDF2C:: @ 80DDF2C
	.string " ...Uh~2c no?\n"
	.string "There~27s no space at all to receive\n"
	.string "any more mail.#P"
	.string " Delete some old mail~2c\n"
	.string "and then come to me to receive\n"
	.asciz "your mail~2c OK?"
	.align 2, 0

gUnknown_80DDFB8:: @ 80DDFB8
	.string " All righty! Connect up\n"
	.string "the #CGGame Link cable#R~2c if you~27d please.\n"
	.asciz "Your friend ready~2c too?"
	.align 2, 0

gUnknown_80DE01C:: @ 80DE01C
	.string "#+Communicating...\n"
	.string "#+Please wait with the power on.\n"
	.string "#+To cancel~2c press {B_BUTTON}.\0"
	.align 2, 0

gUnknown_80DE06C:: @ 80DE06C
	.string " Okeydoke!\n"
	.string "I received your friend~27s #CGSOS Mail#R.#P"
	.asciz " Let me save your adventure."
	.align 2, 0

gUnknown_80DE0C0:: @ 80DE0C0
	.string " Okeydoke! You~27re good to go.\n"
	.string "Just give me a shout when you~27d like\n"
	.asciz "to go rescue your friend."
	.align 2, 0

gUnknown_80DE124:: @ 80DE124
	.string " OK~2c I need you to enter\n"
	.string "the #CGSOS Mail password#R that your\n"
	.asciz "friend gave you."
	.align 2, 0

gUnknown_80DE178:: @ 80DE178
	.string " How do you want to receive\n"
	.asciz "your friend~27s #CGSOS Mail#R?"
	.align 2, 0

gUnknown_80DE1B4:: @ 80DE1B4
	.string " How do you want to send\n"
	.asciz "your #CGA-OK Mail#R?"
	.align 2, 0

gUnknown_80DE1E4:: @ 80DE1E4
	.string " ...Uh~2c no?\n"
	.string "You don~27t have an #CGSOS Mail#R.#P"
	.string " You~27ll need to arrange\n"
	.string "to receive your friend~27s #CGSOS Mail#R first.\n"
	.asciz "That~27s what you need to do."
	.align 2, 0

gUnknown_80DE280:: @ 80DE280
	.string " Okeydoke!\n"
	.asciz "Let me show you to the rescue site."
	.align 2, 0

gUnknown_80DE2B0:: @ 80DE2B0
	.string " ...Uh~2c no?\n"
	.string "Doesn~27t look like you can go to the dungeon\n"
	.string "named in this #CGSOS Mail#R.#P"
	.string " Come see me about doing\n"
	.string "this rescue when you can actually go\n"
	.asciz "to that dungeon~2c all right?"
	.align 2, 0

gUnknown_80DE368:: @ 80DE368
	.string " ...Uh~2c no?\n"
	.string "You~27ve blown this rescue mission too\n"
	.string "often. Your friend~27s team is beyond help.#P"
	.string " I~27m sorry to say this~2c\n"
	.string "but you~27ll have to tell your friend that\n"
	.asciz "your rescue attempts failed."
	.align 2, 0

gUnknown_80DE430:: @ 80DE430
	.string " Okeydoke.\n"
	.string "I~27ll need you to choose the #CGSOS Mail#R\n"
	.asciz "for you to go on a rescue mission."
	.align 2, 0

gUnknown_80DE48C:: @ 80DE48C
	.string " What kind of mail do you\n"
	.asciz "want to delete?"
	.align 2, 0

gUnknown_80DE4B8:: @ 80DE4B8
	.string " All righty. Choose\n"
	.asciz "the #CGSOS Mail#R you don~27t need."
	.align 2, 0

gUnknown_80DE4F0:: @ 80DE4F0
	.string " ...Uh~2c no?\n"
	.asciz "You don~27t have any #CGSOS Mail#R."
	.align 2, 0

gUnknown_80DE524:: @ 80DE524
	.string " If you want a reward~2c #C2don~27t\n"
	.string "delete an A-OK Mail#R before getting a\n"
	.string "#CGThank-You Mail#R back for it.#P"
	.string " #C2Be careful#R if you~27re going\n"
	.string "to delete any #CGA-OK Mail#R.#P"
	.string " Okeydoke.\n"
	.string "Choose an #CGA-OK Mail#R\n"
	.asciz "you don~27t need anymore."
	.align 2, 0

gUnknown_80DE614:: @ 80DE614
	.string " ...Uh~2c no?\n"
	.asciz "You don~27t have any #CGA-OK Mail#R."
	.align 2, 0

gUnknown_80DE648:: @ 80DE648
	.string " Uh~2c OK.\n"
	.string "So~2c you want me to delete every piece\n"
	.asciz "of mail that you have."
	.align 2, 0

gUnknown_80DE694:: @ 80DE694
	.string " ...Uh~2c no?\n"
	.string "You don~27t have a single piece of\n"
	.asciz "mail on you!"
	.align 2, 0

gUnknown_80DE6D4:: @ 80DE6D4
	.string " So~2c delete all your #CGSOS Mail#R~2c\n"
	.string "#CGA-OK Mail#R~2c and your #CGThank-You Mail#R?\n"
	.asciz "You~27re absolutely~2c positively sure?"
	.align 2, 0

gUnknown_80DE754:: @ 80DE754
	.string " If I delete any mail~2c it~27s\n"
	.string "gone forever and ever. Bye-bye.\n"
	.asciz "You~27re really~2c really sure now?"
	.align 2, 0

gUnknown_80DE7B8:: @ 80DE7B8
	.string " OK~2c then.\n"
	.asciz "Let me save your adventure now."
	.align 2, 0

gUnknown_80DE7E8:: @ 80DE7E8
	.asciz " Okeydoke. That~27s all done."
	.align 2, 0

gUnknown_80DE808:: @ 80DE808
	.string " Do you want to delete\n"
	.asciz "any other mail?"
	.align 2, 0

gUnknown_80DE830:: @ 80DE830
	.string " Okeydoke.\n"
	.asciz "I~27ll delete #CGevery piece of mail#R."
	.align 2, 0

gUnknown_80DE864:: @ 80DE864
	.string " Okeydoke.\n"
	.string "Every bit of mail has been deleted.#P"
	.asciz " Let me save your adventure."
	.align 2, 0

gUnknown_80DE8B4:: @ 80DE8B4
	.string " Well~2c hello~2c there!\n"
	.string "This is the #CGFriend Rescue#R counter.\n"
	.asciz "What can I help you with today?"
	.align 2, 0

gUnknown_80DE918:: @ 80DE918
	.string " Help you with anything\n"
	.asciz "else today?"
	.align 2, 0

gUnknown_80DE93C:: @ 80DE93C
	.asciz " Come again anytime!"
	.align 2, 0

gUnknown_80DE954:: @ 80DE954
	.string " ...Uh~2c no?\n"
	.asciz "Something~27s not working right here..."
	.align 2, 0

gUnknown_80DE98C:: @ 80DE98C
	.string " ...Uh~2c no?\n"
	.string "The number of GBA systems isn~27t right.\n"
	.asciz "You~27d better try this again from the top."
	.align 2, 0

gUnknown_80DE9F0:: @ 80DE9F0
	.string " ...Uh~2c no? You~27re not in the\n"
	.string "same mode as your friend.\n"
	.asciz "You~27d better try this again from the top."
	.align 2, 0

gUnknown_80DEA58:: @ 80DEA58
	.string " ...Uh~2c no?\n"
	.string "Your storage space is stuffed full.\n"
	.asciz "You~27d better make room and try again."
	.align 2, 0

gUnknown_80DEAB4:: @ 80DEAB4
	.string " ...Uh~2c no? It looks like\n"
	.string "you received this mail before.\n"
	.asciz "You can~27t get the same mail twice. "
	.align 2, 0

gUnknown_80DEB18:: @ 80DEB18
	.string " ...Uh~2c no?\n"
	.asciz "You~27re not eligible to receive this mail."
	.align 2, 0

gUnknown_80DEB54:: @ 80DEB54
	.string " ...Uh~2c no?\n"
	.string "There~27s no room for you to \n"
	.string "receive any more mail.#P"
	.string " You~27d better delete some\n"
	.string "mail and make room before you come see\n"
	.asciz "me again about receiving new mail."
	.align 2, 0

gUnknown_80DEC00:: @ 80DEC00
	.string " ...Uh~2c no? Looks like your\n"
	.string "friend didn~27t do what needed doing.\n"
	.asciz "You~27d better do this again from the top."
	.align 2, 0

gUnknown_80DEC70:: @ 80DEC70
	.string " ...Uh~2c no?\n"
	.string "This here password looks wrong.\n"
	.asciz "Do you want to try that again?"
	.align 2, 0

gUnknown_80DECC0:: @ 80DECC0
	.string " ...Uh~2c no? This password~27s\n"
	.asciz "not for any #CGSOS Mail#R."
	.align 2, 0

gUnknown_80DECFC:: @ 80DECFC
	.string ": I received the #CGSOS Mail#R.\n"
	.asciz "Your adventure will be saved."
	.align 2, 0

	.asciz "pksdir0"
	.align 2, 0
